kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-argocd-pipeline-claim
  namespace: api-argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:

