kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: api-argocd
   
  name: api-argocd
  labels:
    app: api-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-argocd
  template:
    metadata:
      name: api-argocd
      labels:
        app: api-argocd
    spec:
      volumes:
        - name: emptydirlogs
          emptyDir: {}
      containers:
        - name: microservice-pod 
          volumeMounts:
          - mountPath: /config
            name: volume-qnl65
           
          readinessProbe:
            httpGet:
              path: actuator/health
              port: 8080
              scheme: HTTP
          env:
          - name: JAVA_OPTS
          	value: "-Dspring.config.additional-location=file://config/application.yml"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          imagePullPolicy: Always
          
          image: quay.io/olivier_castanos/ipa
 
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: emptydirlogs
      - configMap:
          defaultMode: 420
          name: api-argocd-cm
        name: volume-qnl65