kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: api-argocd
  name: api-argocd-route
  labels:
    app: api-argocd
spec:
  to:
    kind: Service
    name: api-argocd-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
