kind: Service
apiVersion: v1
metadata:
  namespace: api-argocd
  name: api-argocd-service
  labels:
    app: api-argocd
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api-argocd