apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: api-argocd-trigger
  namespace: api-argocd
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: api-argocd-triggerbinding
  template:
    ref: api-argocd-triggertemplate