warning: Cannot check if git requires authentication.
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: api-argocd
      app.kubernetes.io/component: api-argocd
      app.kubernetes.io/instance: api-argocd
    name: api-argocd
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: api-argocd
      app.kubernetes.io/component: api-argocd
      app.kubernetes.io/instance: api-argocd
    name: api-argocd
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: api-argocd:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/olivierits4u/api-argocd.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:openjdk-17-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: 5giSqYvbISuiEQO13MsE
      type: GitHub
    - generic:
        secret: a0VJ7Dm2j5GX8yG1_-wB
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"api-argocd:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"api-argocd\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: api-argocd
      app.kubernetes.io/component: api-argocd
      app.kubernetes.io/instance: api-argocd
    name: api-argocd
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: api-argocd
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: api-argocd
      spec:
        containers:
        - image: ' '
          name: api-argocd
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: api-argocd
      app.kubernetes.io/component: api-argocd
      app.kubernetes.io/instance: api-argocd
    name: api-argocd
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: api-argocd
  status:
    loadBalancer: {}
kind: List
metadata: {}
